### ISSUE TITLE
Best for short scripts, or for using Swift packages in general?

### ISSUE THREAD

**Issue by sahandnayebaziz** [JohnSundell/Marathon#14]
@JohnSundell, this looks awesome. Thank you for sharing this.

I use Swift on iOS all the time, but I've only tried setting up a Swift executable with the Swift Package Manager a couple times. I'd just like to ask for your take and recommendation. 

Do you think Marathon would work well for managing dependencies not for a short script, but for a Swift server app? 

Forgive the very hasty comparison here, but Marathon looks to me like it could serve a similar role to what NPM does on a basic Node.js app: installing dependencies in just a few moments and updating the list of packages automatically.

Thanks again for sharing this awesome work. I'm sure it will help me in my work soon.

**Comment by JohnSundell** [comment]
Hi @sahandnayebaziz! Happy you like Marathon :)

I wouldn't recommend using Marathon for building an entire server-side app, since that's something you want to leave running in order to handle incoming requests, rather than just executing once as you would with a script.

Using the Swift Package Manager directly is better in that situation, and you can always use [SwiftPlate](https://github.com/johnsundell/swiftplate) to generate framework projects quickly.

Where Marathon shines is to be able to quickly write and run smaller scripts, to link them with dependencies, to create automation such as build tools, and be able to easily share them with your team 👍

**Comment by sahandnayebaziz** [comment]
Wonderful, thank you @JohnSundell :)
