### ISSUE TITLE
[Improvement] [Tests] Make test efficient and less time

### ISSUE THREAD

**Issue by pixyzehn** [JohnSundell/Marathon#35]
Now `swift test` takes about 295s in my env. It's time to reduce the time, so we can focus on more essential parts.

```
Test Suite 'MarathonTests' passed at 2017-04-09 09:07:23.894.
	 Executed 34 tests, with 0 failures (0 unexpected) in 294.578 (294.580) seconds
Test Suite 'MarathonPackageTests.xctest' passed at 2017-04-09 09:07:23.894.
	 Executed 34 tests, with 0 failures (0 unexpected) in 294.578 (294.580) seconds
Test Suite 'All tests' passed at 2017-04-09 09:07:23.894.
	 Executed 34 tests, with 0 failures (0 unexpected) in 294.578 (294.581) seconds
```

**Comment by JohnSundell** [comment]
I'm not sure if we _can_ reduce the time that much. The reason the tests are slow is because they are running the **real** Marathon tool, performing remote clones, updating packages, etc. So that's inherently going to be slower than, for instance, using mocking. I think there's great value in doing the tests using the real deal, since it very accurately simulates the conditions of Marathon being run in the wild.

That being said, we should definetly invest in making Marathon **faster** over all, which will in turn make the tests faster.

**Comment by amlcurran** [comment]
Is there a potential ability or desire to split the test suite into unit tests and integration tests?

**Comment by JohnSundell** [comment]
@amlcurran The problem is that at the moment, they're all pretty much integration tests 😅 I usually rely mostly on unit tests, but for Marathon I wanted to test the real deal - since it relies on so many underlying systems like the Swift Package Manager, the file system, Swift's build system, etc. So not sure how much value unit tests would bring to this project.

One thing we could do is split the test suite up by command. So we'd have `RunTests`, `InstallTests`, etc. That way you could run the tests only for the command you're currently working on, and then just perform a single pass through the entire test suite before submitting a change. That would probably improve the workflow quite a bit.

**Comment by amlcurran** [comment]
Yeah I'd like that second suggestion 👍 the current test file is rather large, and the `MARK:` statements make it well divided enough to split. Would happy to take a look at that later, after looking at #27.

**Comment by JohnSundell** [comment]
Now that we run tests on parallel both locally and on CI, I think that this can be closed. @pixyzehn, @amlcurran, what do you guys think? 🙂

**Comment by pixyzehn** [comment]
@JohnSundell  I'm OK with it👍
