### ISSUE TITLE
Error in Readme

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/Marathon#45]
The README mentions

```
marathon install https://raw.githubusercontent.com/JohnSundell/Marathon-Examples/master/AddSuffix/AddSuffix.swift
```

Currently this is a 404: https://raw.githubusercontent.com/JohnSundell/Marathon-Examples/master/AddSuffix/AddSuffix.swift

**Comment by JohnSundell** [comment]
@rob-nash I just ran the above command and it worked 🤔 The link is also clickable and downloads the file in Safari...

**Comment by rob-nash** [comment]
Have you opened the file ?

**Comment by rob-nash** [comment]
<img width="578" alt="screen shot 2017-04-12 at 19 50 38" src="https://cloud.githubusercontent.com/assets/14126999/24974220/554ccdce-1fb9-11e7-9cf7-523d6262041c.png">

**Comment by kkapitan** [comment]
I think this is due to the wrong link being passed as an argument to `marathon install`. 

The correct url [here](https://raw.githubusercontent.com/JohnSundell/Marathon-Examples/master/AddSuffix/addSuffix.swift) with lowercase `addSuffix.swift`. If you however go to [this](https://raw.githubusercontent.com/JohnSundell/Marathon-Examples/master/AddSuffix/AddSuffix.swift) url with capital `AddSuffix.swift` it states `404: Not Found`.

However it might be good idea to enhance `marathon install` to fail earlier in case of 404 error

**Comment by JohnSundell** [comment]
@kkapitan @rob-nash Ah, that's the problem! Will update the `README` to have the correct casing, thanks guys! 👍

**Comment by JohnSundell** [comment]
`README` updated!
