### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by TofPlay** [JohnSundell/Marathon#7]
Below the title please add badges this help a lot. 

If your component is compatible: 
- with carthage add [![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-brightgreen.svg)](https://github.com/Carthage/Carthage)
- with SwiftPM add [![SwiftPM compatible](https://img.shields.io/badge/SwiftPM-compatible-brightgreen.svg)](https://github.com/apple/swift-package-manager)

Indicated:
- the Swift version ![Swift Version](https://img.shields.io/badge/Swift-3.0-orange.svg)
- Platforms supported ![Plaforms](https://img.shields.io/badge/Platforms-Linux%20%7C%20macOS%20%7C%20iOS%20%7C%20WatichOS%20%7C%20tvOS-lightgrey.svg)
- License ![License MIT](https://img.shields.io/badge/License-MIT-lightgrey.svg)

**Comment by JohnSundell** [comment]
I do have these badges on all my other open source projects that are libraries, but for something like Marathon - which is a command line tool - I don't think they make much sense.

The license is already clearly visible in the GitHub UI, and since it's a command line tool it's not going to be used with any dependency management systems. The fact that it's Swift 3 is an implementation detail that's only relevant to contributors of the project (for which I'm planning to publish a contribution guide for soon).

Will close this, but thanks a lot for your suggestion 🙂

**Comment by TofPlay** [comment]
> I don't think they make much sense

It's make sense but It's up to you. 
For example actually we don't know if your tool is compatible with macOS or Linux, or even both. We don't know if marathon Is it compatible with Swift 3.0.2 or also with Swift 3.1.
