### ISSUE TITLE
Make it easy to write tests against your scripts

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/Marathon#77]
Sometimes you want to write tests for your scripts. For example if you're making something publically available, or if the script goes through many iterations, or if it grows in complexity. Although at some point it'd be better to use the Swift Package Manager directly and just use `swift test` to perform tests, it would be very nice if Marathon included lightweight support for running tests using the `XCTest` framework.

**Proposal: Introducing a `test` command**

Running `marathon test MyScript.swift` will look for a file called `MyScriptTests.swift`, and do the following:

- If it exists, copy it into the script's package directory and run `swift test` to run the tests.
- If it doesn't exist, create it and open the script's package for editing in Xcode, so that tests can be written.

**Extension to the `create` and `edit` commands**

We should also extend `create` and `edit` to support creating a script package that already contains test support. The proposal is to introduce a `--test` flag that can be passed to these commands. So for example `marathon create MyScript.swift` will create both `MyScript.swift` and `MyScriptTests.swift`.

**Comment by JohnSundell** [comment]
@clayellis @garricn we've been talking about testing scripts before, what do you guys think about this proposal? Would it be a nice way to unit test your scripts? 😄

**Comment by garricn** [comment]
I certainly have had the desire to write tests for my scripts. I'm just unsure how that would event work so it's hard for me to have an opinion on either marathon ought to help.

The way I was testing Twix, was by just manually running it on some files. Ideally, I would be able to run tests in my development environment. I set out to do it once, but I wasn't sure where to begin.

What do your current marathon script testing workflows look like?

**Comment by clayellis** [comment]
I think that sounds like a great workflow for testing. (I think with scripting being such a lightweight process in and of itself, the workflow is equally as important as the implementation and should remain a high priority - fast, straightforward, and as frictionless as possible.) 

So just to clarify, after running `marathon create MyScript --test` we'd create both `MyScript.swift` and `MyScriptTests.swift` at the same level. Whereas `marathon create MyScript` would only create `MyScript.swift`? And `marathon edit MyScript --test` would begin editing `MyScriptTests.swift` in Xcode?

> Running marathon test MyScript.swift will look for a file called MyScriptTests.swift, and do the following:
>
> - If it exists, copy it into the script's package directory and run swift test to run the tests.
> - If it doesn't exist, create it and open the script's package for editing in Xcode, so that tests can be written.

My only concern with the above, is that `marathon test MyScript` is dependent on state (whether MyScriptTests.swift exists or not) and does two pretty different things depending on state, editing a file vs. running tests. The first time a user runs `marathon test MyScript` and sees that it opens Xcode they'll think that's the way to open tests so the second time they use it, they'll probably be using it with the intention to edit the tests, but instead they'll just run the tests which could be confusing. 

We could cut back on that confusion in two different ways:
1. If `MyScriptTests.swift` doesn't exist and the user runs `marathon test MyScript`, display a prompt `⚠️ MyScript doesn't have any tests to run. ✅ Would you like to create tests (MyScriptTests.swift)? y/n` Then the user enters `y` and we display: `👍🏼 Created MyScriptTests.swift ✏️ Opening MyScriptTests.swift ℹ️ You can edit MyScriptTests.swift by running marathon edit MyScript --test`. That way we make it clear that `marathon test MyScript` is meant for running tests and creating/editing a file through this command is a first-time only thing.
2. Or... if `MyScriptTests.swift` doesn't exist and the user runs `marathon test MyScript`, we could just prompt the user to use the `create --test` command directly. `⚠️ MyScript doesn't have any tests to run. Create tests using `marathon create MyScript --test`.

I'm not sure which one I like better. What do you think?

@garricn Currently, my workflow has been to work in a playground with an `XCTestCase` subclass containing tests at the bottom of my file and I work on the core logic above and then copy/paste over to my script file (after running `marathon edit SomeScript`). It works, but it's super cumbersome. And it's a pain if I forget to close the Xcode window I was editing my script in previously after I hit enter to commit to Marathon and then I go and paste new work into it. That's for another issue thread, though. 

I would consider limiting `marathon test MyScript` to testing alone and not creating `MyScriptTest.swift` if it doesn't already exist in order to give the command a single responsibility, make it more predictable. Though, it could prompt the user `MyScript doesn't have any tests. Create tests using "marathon create MyScript --test".` Unless you think that would only add friction. In which case we could print

**Comment by JohnSundell** [comment]
Totally agree with you @clayellis in that the testing process need to be lightweight and easy to get into. Also agree that it's wierd that `marathon test` does different things depending on state (will also make it harder to use it on CI, etc) 👍 

I think I like option 2 the most, since it gives the user a clear action to take, and would be simpler to implement. What I also like about it is that it "teaches" the user what commands to run, instead of running them semi-automagically 😄 

As for the actual testing, we need to provide a little bit of extra infrastructure to enable a script to be run (since it's written in the global scope). I'm thinking something like this:

```swift
import XCTest

class StringAddingScriptTests: XCTestCase {
    func testAddingStrings() throws {
        // Marathon provides the 'runScript' method through an extension on 'XCTestCase'
        let output = runScript(withArguments: ["Hello ", "World"])
        XCTAssertEqual(output, "Hello World")
    }
}
```

What do you guys think?

**Comment by JohnSundell** [comment]
@pixyzehn @darthpelo @alexaubry do you have any thoughts on this? 😄

**Comment by darthpelo** [comment]
@JohnSundell I agree with you about the option 2 👍

**Comment by clayellis** [comment]
@JohnSundell sounds good, option two sounds like the way to go. As for the implementation, that seems like a good way to do it. Will `runScript(withArguments:)` need to be added to [MarathonCore/Script.swift](https://github.com/JohnSundell/Marathon/blob/5eed45ab7a2c4b4af952722a9d8e84a2cde4ce33/Sources/MarathonCore/Script.swift)? This would also give users the ability to test internal logic (without running the entire script) if needed, correct?

**Comment by JohnSundell** [comment]
@clayellis The thing is that `MarathonCore` is not available to scripts unless you add it using `marathon add`, which I don't think should be a requirement. Instead, when we generate the Swift package for the script under testing, we should add a `XCTestCase+Marathon.swift` file to it that contains the `runScript` method (and any other utilities we want to add in the future). So the `XCTestCase+Marathon.swift` file won't be a part of the `MarathonCore` module, rather it will be genereted when needed.

For the implementation, I think the testing functionality can be implemented in the file you referenced, as a `test()` method, that sets everything up and runs the tests using `swift test`.

**Comment by clayellis** [comment]
Ohhh, okay gotcha. So in order to get started on this we need to (so far):

 - Introduce a `test` command in [Command.swift](https://github.com/JohnSundell/Marathon/blob/master/Sources/MarathonCore/Command.swift)
 - Create a `TestTask`
 - Generate `XCTestCase+Marathon.swift` from  `TestTask`
 - Add a `--test` flag to [CreateTask](https://github.com/JohnSundell/Marathon/blob/master/Sources/MarathonCore/Create.swift) and [EditTask](https://github.com/JohnSundell/Marathon/blob/master/Sources/MarathonCore/Edit.swift)
 - Add `test()` to [Script](https://github.com/JohnSundell/Marathon/blob/5eed45ab7a2c4b4af952722a9d8e84a2cde4ce33/Sources/MarathonCore/Script.swift)

**Comment by JohnSundell** [comment]
@clayellis Exactly 👍 You wanna work on this? 😄

**Comment by clayellis** [comment]
I'll get started tomorrow morning!

**Comment by JohnSundell** [comment]
Amazing! Let me know if you need any assistance, happy to help 🙂

**Comment by pixyzehn** [comment]
@JohnSundell Sorry for late. I agree with option2 rather than option1. Looking forward to it:)

**Comment by garricn** [comment]
@clayellis Thank you for the reply. This all sounds great to me! I look forward to using this feature and learning more about how to test my scripts.

**Comment by clayellis** [comment]
If a script (`MyScript`) doesn't exist and a user runs `marathon create MyScript --test` I'm going to create the script as usual and add a `MyScriptTests.swift`. (Obviously, running the same command if `MyScript` already existed would only create the tests file.) Unless you guys think the behavior should be any different @JohnSundell @pixyzehn @garricn ?

**Comment by clayellis** [comment]
I'm leaning towards naming the flags `--tests` instead of `--test` since you write *tests* for code, not just *a* test. What think ye?

**Comment by JohnSundell** [comment]
@clayellis Sounds great 👍

**Comment by clayellis** [comment]
@JohnSundell when you said this
> XCTestCase+Marathon.swift ... will be generated when needed.
Did you envision that happening during the `create MyScript --tests` phase or the `test MyScript` phase? How will `runScript(withArguments:)` be available in `MyScriptTests.swift`? I was thinking for a second that we would generate the extension in the same directory as the original script/tests files so that it would be available that way, but then we're missing the tools we need from Marathon to run the actual tests (or rather, we'd be exposing all of that logic.)

**Comment by clayellis** [comment]
@JohnSundell would you like to close this issue out given the comment about limiting scope on #88?

**Comment by JohnSundell** [comment]
Yes, great call @clayellis 👍 Thanks!
